In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import random

In [2]:
#### ATTEMPT 1
#Check if all elements in the column are equal 
def winner(matrix):
    for i in range(len(matrix)):
        column = [row[i] for row in matrix]
        line = matrix[i]
        #print("column is", column)
        #print("row is", line)
        if all(x == 0 for x in column): 
            print("Entries in column", i, "are all equal to 0")
            print("Indeed the determinant is equal to", np.linalg.det(matrix))
            break
        elif all(x == 0 for x in line): 
            print("Entries in line",i, "has all entries equal to 0")
            print("Indeed the determinant is equal to", np.linalg.det(matrix))
            break

n = 5
matrix = np.random.randint(low=0, high=2, size=(n, n))
print(matrix)
winner(matrix)
if(np.linalg.det(matrix)!= 0.0):
    print("Determinant is equal to", np.linalg.det(matrix))

[[1 0 1 1 0]
 [0 1 1 0 0]
 [1 0 0 1 1]
 [0 1 1 0 0]
 [1 0 0 1 1]]


From some of the examples above, we notice that the random matrices produce matrix with determinant $0$ even though there aren't any lines or rows with all $0$s.

For example the following $5 \times 5$ matrix:

$$\begin{pmatrix} 
0 & 0 & 0 & 1 & 0 \\ 
0 & 1 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 & 0 \\
1 & 1 & 0 & 1 & 1 \\
1 & 1 & 0 & 0 & 1 \\
\end{pmatrix}$$


Notice here that column $0$ is equal to column $4$, following Python indexing that starts form $0$, hence we implement the function above to check whether any 2 rows or colum
Hence another attempt is based on implementing the function above such that it checks whether any 2 rows or columns are equal.

In [3]:
##### ATTEMPT 2

def winner(matrix):
    for i in range(len(matrix)):
        for j in range(i+1, len(matrix)):
            column = matrix[:,i]
            col2 = matrix[:,j]
            line = matrix[i]
            line2 = matrix[j]
            #Check if all elements in the column are equal 
            if all(x == 0 for x in column): 
                print("Entries in column", i, "are all equal to 0")
                break
            elif all(x == 0 for x in line): 
                print("Entries in line",i, "has all entries equal to 0")
                break
            elif np.array_equal(column, col2):
                print("column",i,"is equal to column",j)
                break
            elif np.array_equal(line, line2):
                print("row",i,"is equal to row",j)
                break
            
n = 5
matrix = (np.random.randint(low=0, high=2, size=(n, n)))

print(matrix)
winner(matrix)
print("Determinant is equal to", np.linalg.det(matrix))

[[0 0 1 0 1]
 [1 0 1 0 1]
 [1 0 0 1 0]
 [0 1 0 0 0]
 [1 1 0 0 1]]
Determinant is equal to -1.0


One of the examples that came up with the random generation, shows no similar rows or columns but still has determinant $0$ hence, the fame could still be won by the player using only $0$:
$$\begin{pmatrix} 
0 & 1 & 0 & 0 & 0 \\ 
0 & 0 & 1 & 1 & 0 \\
0 & 1 & 1 & 0 & 1 \\
0 & 1 & 1 & 1 & 0 \\
1 & 1 & 1 & 0 & 1 \\
\end{pmatrix}$$

Another of the condition for which the determinant is $0$, is given by linear dependende of columns / rows.
In this case notice that sum of all entries of row $0$ with row $4$ is equal to the sum of all entries of row $1$ with either row $2$ or row $3$.

And that column $4$ = column $2$ - column $3$

Hence check that by implementing the function written above

In [4]:
##### ATTEMPT 3

def winner(matrix):
    for i in range(len(matrix)):
        column = matrix[:,i]
        line = matrix[i]        
        #Check if all elements in the column are equal to 0 
        if all(x == 0 for x in column): 
            print("Entries in column", i, "are all equal to 0")
            break
        elif all(x == 0 for x in line): 
            print("Entries in line",i, "has all entries equal to 0")
            break
        for j in range(i+1, len(matrix)):
                col2 = matrix[:,j]
                line2 = matrix[j]              
                #Check if any 2 columns or rows are equal
                if np.array_equal(column, col2):
                    print("column",i,"is equal to column",j)
                    break
                elif np.array_equal(line, line2):
                    print("row",i,"is equal to row",j)
                    break
                for k in range(j+1,len(matrix)):
                    col3 = matrix[:,k]
                    line3 = matrix[k] 
                    #Check if any column / row is a linear combination of the other
                    if np.array_equal(col3, col2+column):
                        print("the column", k, "is a linear combination of column", i,"and",j)
                        break
                    elif np.array_equal(col3, col2-column):
                        print("the column", k, "is a linear combination of column", i,"and",j)
                        break
                    elif np.array_equal(col3, -col2 + column):
                        print("the column", k, "is a linear combination of column", i,"and",j)
                        break
                    elif np.array_equal(line3, line +line2):
                        print("row", k, "is a linear combination of row", i,"and",j)
                        break
                    elif np.array_equal(line3, line -line2):
                        print("row", k, "is a linear combination of row", i,"and",j)
                        break
                    elif np.array_equal(line3,-line +line2):
                        print("row", k, "is a linear combination of row", i,"and",j)
                        break

#for n > 2
n = 4
matrix = (np.random.randint(low=0, high=2, size=(n, n)))

print(matrix)
winner(matrix)
print("Determinant is equal to", np.linalg.det(matrix))

[[0 1 1 0]
 [0 1 1 0]
 [0 0 1 1]
 [0 0 0 0]]
Entries in column 0 are all equal to 0
Determinant is equal to 0.0


One of the above condtions is true any time the determinant of the matrix is 0.

In [5]:
def generate_matrix(n):
    matrix = np.zeros((n, n), dtype=int)

        
    # Distribute ones randomly across rows
    num_ones = n * n // 2
    for i in range(n):
        if i < n - 1:  
            ones_count = random.randint(0, num_ones)
            matrix[i, :ones_count] = 1
            num_ones -= ones_count
        else:
            matrix[i, :num_ones] = 1
    # Shuffle rows to ensure randomness
    np.random.shuffle(matrix)
    
    # Ensure the difference in number of 0s and 1s is at most 1
    num_zeros = np.sum(matrix == 0)
    num_ones = np.sum(matrix == 1)
    if abs(num_zeros - num_ones) > 1:
        # Reshuffle until the condition is met
        return generate_matrix(n)

    # Swap pairs of rows to ensure at least two pairs with equal sums
    for i in range(0, n-1, 2):
        matrix[[i, i+1]] = matrix[[i+1, i]]
        
    # Shuffle columns to add randomness to each row
    matrix = matrix[:, np.random.permutation(matrix.shape[1])]
        
    return matrix

# Example usage:
n = 10
matrix = generate_matrix(n)

# Display matrix
print(f"Generated {n}x{n} Matrix:")
print(matrix)
print(np.linalg.det(matrix))

Generated 10x10 Matrix:
[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 1 1 1 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 1 0]
 [0 0 0 1 0 1 0 0 1 0]
 [0 0 0 1 1 1 1 1 1 0]
 [0 0 0 1 1 1 1 1 1 0]]
0.0


In [31]:
def generate_matrix(n):
    while True:
        # Initialize a matrix with zeros
        matrix = np.zeros((n, n), dtype=int)

        # Assign 1s randomly
        num_ones = random.randint(0, n**2)
        for _ in range(num_ones):
            i, j = random.randint(0, n-1), random.randint(0, n-1)
            while matrix[i, j] == 1:  #Avoid reassigning 1 to an already assigned cell
                i, j = random.randint(0, n-1), random.randint(0, n-1)
            matrix[i, j] = 1

        # Ensure the number of 0s is either equal to the number of 1s or at most one more
        num_zeros = np.count_nonzero(matrix == 0)
        num_ones = np.count_nonzero(matrix == 1)
        if abs(num_zeros - num_ones) > 1:
            continue

        # Modify one row to be a linear combination of the others
        row_to_modify = random.randint(0, n-1)
        matrix[row_to_modify] = np.sum(matrix, axis=0) % 2
        
        # Ensure no row or column contains all 0s or all 1s
        row_has_all_zeros_or_ones = any(np.all(row == 0) or np.all(row == 1) for row in matrix)
        col_has_all_zeros_or_ones = any(np.all(col == 0) or np.all(col == 1) for col in matrix.T)
        if row_has_all_zeros_or_ones or col_has_all_zeros_or_ones:
            continue

        # Check if the determinant is 0
        if np.linalg.det(matrix) == 0:
            return matrix

# Example usage:
n = 9
matrix = generate_matrix(n)

# Display matrix
print(f"Generated {n}x{n} Matrix:")
print(matrix)

# Check determinant
print("Determinant:", np.linalg.det(matrix))


Generated 9x9 Matrix:
[[1 0 1 0 1 0 0 1 0]
 [1 0 0 0 0 0 1 0 0]
 [1 1 1 1 0 1 1 0 1]
 [0 0 1 1 0 1 1 1 1]
 [1 1 0 1 0 0 0 1 1]
 [1 0 1 1 0 0 0 1 1]
 [1 0 0 1 1 0 1 0 1]
 [0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 1]]
Determinant: 0.0
